// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAASa-gvm1SVenqYVzVDO4xlMzGFxZi8qM',
    appId: '1:26157639393:android:3a7d8ae5151649fd4379a0',
    messagingSenderId: '26157639393',
    projectId: 'pushnotification-cfc29',
    storageBucket: 'pushnotification-cfc29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqkLHjqZmWQOysfGFydv_thKC5drcnhdM',
    appId: '1:26157639393:ios:9e390a16cdf629144379a0',
    messagingSenderId: '26157639393',
    projectId: 'pushnotification-cfc29',
    storageBucket: 'pushnotification-cfc29.appspot.com',
    iosClientId: '26157639393-4r3v442u695eqdlqdqnmddneevqih5d1.apps.googleusercontent.com',
    iosBundleId: 'com.pushnotifiacation.pushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqkLHjqZmWQOysfGFydv_thKC5drcnhdM',
    appId: '1:26157639393:ios:9e390a16cdf629144379a0',
    messagingSenderId: '26157639393',
    projectId: 'pushnotification-cfc29',
    storageBucket: 'pushnotification-cfc29.appspot.com',
    iosClientId: '26157639393-4r3v442u695eqdlqdqnmddneevqih5d1.apps.googleusercontent.com',
    iosBundleId: 'com.pushnotifiacation.pushnotification',
  );
}
